# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [6]:
# Import torch
import torch

# Create random tensor
X = torch.rand(7, 7)
X, X.shape

(tensor([[0.3997, 0.8570, 0.2414, 0.8421, 0.6616, 0.9041, 0.6638],
         [0.4537, 0.6026, 0.2867, 0.5447, 0.6681, 0.0083, 0.8390],
         [0.5117, 0.9628, 0.0634, 0.9302, 0.8686, 0.8896, 0.6431],
         [0.6121, 0.3703, 0.2086, 0.2682, 0.5917, 0.5867, 0.9085],
         [0.6905, 0.5268, 0.0181, 0.1411, 0.6808, 0.2476, 0.7812],
         [0.6877, 0.2988, 0.2543, 0.5885, 0.2264, 0.6342, 0.9692],
         [0.9777, 0.2112, 0.1555, 0.3519, 0.9518, 0.4585, 0.9596]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [7]:
# Create another random tensor
Y = torch.rand(1,7)
# Perform matrix multiplication 
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[3.1625],
         [2.0631],
         [3.4805],
         [2.1646],
         [1.8757],
         [2.2151],
         [2.4201]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [9]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(7, 7)
Y = torch.rand(1, 7)

# Matrix multiply tensors
Z = X @ Y.T
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [27]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
    device = "cuda" 
else: "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
print(tensor_A, tensor_A.device)
print(tensor_B, tensor_B.device)


Device: cpu
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) cpu
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]]) cpu



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [21]:
# Perform matmul on tensor_A and tensor_B
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, device

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

### 8. Find the maximum and minimum values of the output of 7.

In [29]:
# Find max
max = tensor_C.max()
# Find min
min = tensor_C.min()
max, min

tensor(0.3647)

### 9. Find the maximum and minimum index values of the output of 7.

In [30]:
# Find arg max
maxIndex = tensor_C.argmax()

# Find arg min
minIndex = tensor_C.argmin()
maxIndex, minIndex

(tensor(3), tensor(0))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [46]:
# Set seed
torch.manual_seed(7)

# Create random tensor
D = torch.rand(1, 1, 1, 10)
# Remove single dimensions
E = D.squeeze()

# Print out tensors and their shapes
print(D, D.shape)
print(E, E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
